# Generated by Django 3.0.1 on 2019-12-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20191222_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='describe',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='author',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='name',
        ),
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='hello', max_length=200),
        ),
    ]
